# Created with package:mono_repo v2.1.0
language: dart

# Custom configuration
before_install:
  - "wget -O protoc.zip https://github.com/protocolbuffers/protobuf/releases/download/v3.6.1/protoc-3.6.1-linux-x86_64.zip"
  - "unzip -d protoc protoc.zip"
  - "export PATH=$PWD/protoc/bin:$PATH"
  - echo $PATH
  - "echo \"dependency_overrides: {protobuf: {path: ../protobuf}}\" >> protoc_plugin/pubspec.yaml"
os:
  - linux
  - osx
  - windows

jobs:
  include:
    - stage: format_analyzer_tests
      name: "SDK: stable; PKG: api_benchmark; TASKS: [`./compile_protos.sh`, `dartfmt -n --set-exit-if-changed .`, `dartanalyzer --fatal-warnings .`]"
      dart: stable
      env: PKGS="api_benchmark"
      script: ./tool/travis.sh command_0 dartfmt dartanalyzer_0
    - stage: format_analyzer_tests
      name: "SDK: stable; PKG: protobuf; TASKS: `dartanalyzer --fatal-warnings .`"
      dart: stable
      env: PKGS="protobuf"
      script: ./tool/travis.sh dartanalyzer_0
    - stage: format_analyzer_tests
      name: "SDK: dev; PKG: protobuf; TASKS: `dartanalyzer --fatal-infos --fatal-warnings .`"
      dart: dev
      env: PKGS="protobuf"
      script: ./tool/travis.sh dartanalyzer_1
    - stage: format_analyzer_tests
      name: "SDK: stable; PKG: protobuf; TASKS: `dartfmt -n --set-exit-if-changed .`"
      dart: stable
      env: PKGS="protobuf"
      script: ./tool/travis.sh dartfmt
    - stage: format_analyzer_tests
      name: "SDK: dev; PKG: protobuf; TASKS: `pub run test`"
      dart: dev
      env: PKGS="protobuf"
      script: ./tool/travis.sh test
    - stage: format_analyzer_tests
      name: "SDK: stable; PKG: protobuf; TASKS: `pub run test`"
      dart: stable
      env: PKGS="protobuf"
      script: ./tool/travis.sh test
    - stage: format_analyzer_tests
      name: "SDK: dev; PKG: protoc_plugin; TASKS: [`make protos`, `dartanalyzer --fatal-infos --fatal-warnings .`]"
      dart: dev
      env: PKGS="protoc_plugin"
      script: ./tool/travis.sh command_1 dartanalyzer_1
    - stage: format_analyzer_tests
      name: "SDK: stable; PKG: protoc_plugin; TASKS: [`make protos`, `dartfmt -n --set-exit-if-changed .`, `dartanalyzer --fatal-warnings .`]"
      dart: stable
      env: PKGS="protoc_plugin"
      script: ./tool/travis.sh command_1 dartfmt dartanalyzer_0
    - stage: format_analyzer_tests
      name: "SDK: dev; PKG: protoc_plugin; TASKS: [`make protos`, `pub run test`]"
      dart: dev
      env: PKGS="protoc_plugin"
      script: ./tool/travis.sh command_1 test
    - stage: format_analyzer_tests
      name: "SDK: stable; PKG: protoc_plugin; TASKS: [`make protos`, `pub run test`]"
      dart: stable
      env: PKGS="protoc_plugin"
      script: ./tool/travis.sh command_1 test
    - stage: format_analyzer_tests
      name: "SDK: stable; PKG: query_benchmark; TASKS: [`./compile_protos.sh`, `dartfmt -n --set-exit-if-changed .`, `dartanalyzer --fatal-warnings .`]"
      dart: stable
      env: PKGS="query_benchmark"
      script: ./tool/travis.sh command_0 dartfmt dartanalyzer_0

stages:
  - format_analyzer_tests

# Only building master means that we don't run two builds for each pull request.
branches:
  only:
    - master

cache:
  directories:
    - "$HOME/.pub-cache"
