name: protoc-plugin
version: 0.1.0
authors:
- Dart Team <misc@dartlang.org>
description: Protoc compile to generate Dart code
homepage: https://github.com/dart-lang/protoc-plugin
environment:
  sdk: '>=0.5.13'
dependencies:
  protobuf:
    git: git://github.com/dart-lang/dart-protobuf.git
    version: '>=0.1.0'
dev_dependencies:
  unittest: any
