name: protobuf
version: 0.7.2+1
author: Dart Team <misc@dartlang.org>
description: Runtime library for protocol buffers support.
homepage: https://github.com/dart-lang/protobuf
environment:
  sdk: '>=2.0.0-dev.17.0 <2.0.0'
dependencies:
  fixnum: '>=0.9.0 <0.11.0'
dev_dependencies:
  test: '>=0.12.0 <0.13.0'
