name: protoc_plugin
version: 0.10.2
author: Dart Team <misc@dartlang.org>
description: Protoc compiler plugin to generate Dart code
homepage: https://github.com/dart-lang/dart-protoc-plugin
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  fixnum: ^0.10.5
  path: ^1.0.0
  protobuf: ^0.10.2
  dart_style: ^1.0.6
dev_dependencies:
  test: ^1.3.0
executables:
  protoc-gen-dart: protoc_plugin
