name: protobuf
version: 0.3.0
authors:
- Dart Team <misc@dartlang.org>
description: Runtime library for protobuf support.
homepage: https://github.com/dart-lang/dart-protobuf
environment:
  sdk: '>=0.8.7'
dependencies:
  crypto: '>=0.7.5'
  fixnum: '>=0.7.5'
dev_dependencies:
  unittest: any
