name: protobuf
version: 0.5.1+3
author: Dart Team <misc@dartlang.org>
description: Runtime library for protobuf support.
homepage: https://github.com/dart-lang/dart-protobuf
environment:
  sdk: '>=1.13.0 <2.0.0'
dependencies:
  fixnum: '>=0.9.0 <0.11.0'
dev_dependencies:
  test: '>=0.12.0 <0.13.0'
