name: protobuf
version: 0.9.0+1
author: Dart Team <misc@dartlang.org>
description: Runtime library for protocol buffers support.
homepage: https://github.com/dart-lang/protobuf
environment:
  sdk: '>=2.0.0-dev.17.0 <3.0.0'
dependencies:
  fixnum: '>=0.9.0 <0.11.0'
dev_dependencies:
  test: '>=1.2.0'
  benchmark_harness: any
  js: any
