name: protobuf
version: 1.0.0
author: Dart Team <misc@dartlang.org>
description: >
  Runtime library for protocol buffers support.
  Use https://pub.dartlang.org/packages/protoc_plugin to generate dart code for your '.proto' files.
homepage: https://github.com/dart-lang/protobuf

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  fixnum: ^0.10.9

dev_dependencies:
  test: '>=1.2.0'
  benchmark_harness: any
  js: any
  pedantic: ^1.0.0
