name: protobuf
version: 4.1.0
description: >-
  Runtime library for protocol buffers support. Use with package:protoc_plugin
  to generate Dart code for your '.proto' files.
repository: https://github.com/google/protobuf.dart/tree/master/protobuf

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  collection: ^1.15.0
  fixnum: ^1.0.0
  meta: ^1.7.0

dev_dependencies:
  dart_flutter_team_lints: ^1.0.0
  matcher: ^0.12.11
  test: ^1.16.0
