name: protoc_plugin
version: 20.0.0
description: Protoc compiler plugin to generate Dart code
homepage: https://github.com/dart-lang/protobuf

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  fixnum: ^1.0.0
  path: ^1.8.0
  protobuf: ^2.0.0
  dart_style: ^1.0.6

dev_dependencies:
  test: ^1.16.0
  pedantic: ^1.10.0
  matcher: ^0.12.10
  collection: ^1.15.0
  grpc: ^3.0.0

executables:
  protoc-gen-dart: protoc_plugin
