name: protoc_plugin
version: 20.0.0-nullsafety.0
description: Protoc compiler plugin to generate Dart code
homepage: https://github.com/dart-lang/protobuf

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  fixnum: '>=0.10.9 <2.0.0'
  path: ^1.0.0
  protobuf: '>=1.1.0 <2.0.0'
  dart_style: ^1.0.6

dev_dependencies:
  test: ^1.3.0
  pedantic: ^1.9.2

executables:
  protoc-gen-dart: protoc_plugin
