name: protoc_plugin
version: 21.1.0
description: A protobuf protoc compiler plugin used to generate Dart code.
repository: https://github.com/google/protobuf.dart/tree/master/protoc_plugin

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  fixnum: ^1.0.0
  path: ^1.8.0
  protobuf: ^3.1.0

dev_dependencies:
  collection: ^1.15.0
  dart_flutter_team_lints: ^1.0.0
  matcher: ^0.12.10
  test: ^1.16.0

executables:
  protoc-gen-dart: protoc_plugin
