name: protoc_plugin
version: 13.0.1
author: Dart Team <misc@dartlang.org>
description: Protoc compiler plugin to generate Dart code
homepage: https://github.com/dart-lang/protobuf

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  fixnum: ^0.10.5
  path: ^1.0.0
  protobuf: ^0.10.7
  dart_style: ^1.0.6

dev_dependencies:
  build: ^1.0.0
  build_runner: ^1.0.0
  build_web_compilers: ^0.4.0
  glob: ^1.1.7
  test: ^1.3.0
  yaml: ^2.1.15

executables:
  protoc-gen-dart: protoc_plugin
